# ░░░░░░░░░░░░░░░   RegionPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/regionplus.76878/
#  Wiki: https://github.com/momoservertw/RegionPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 4
Debugging: false

General:
  Settings:
    Features:
      # Changed these options need to restart the server.
      Hook:
        Residence: true
        MultiverseCore: true
        SurvivalMechanics: true
        Vehicles: true

# Some normal features to improve CMI and Residence.
# More information: https://github.com/momoservertw/RegionPlus/wiki/World
World:
  Enable: false
  Prevent:
    Enable: true
    Creeper-Block-Damage: true
    Enderdragon-Block-Damage: true
    Explode-Block-Damage: false
    Fire-Spread: true

# Adding more features for Residence.
# More information: https://github.com/momoservertw/RegionPlus/wiki/Residence
Residence:
  Enable: false
  # Fixed some bugs and improved the player's gaming experience.
  Prevent:
    Enable: true
    Potion-Damage: true
    Zombie-Door-Destruction: true
    Enderman-Pickup-Block: true
    Painting-Destroy: true
    Item-Frame-Destroy: true
    Armor-Stand-Destroy: true
    Ender-Crystal-Destroy: true
    Block-Damage: true
  # To limit the total size of player's residences.
  # The physical area may be at the same location, this feature will only check the main area size.
  Points:
    Enable: false
    Settings:
      Select-Info: true
      # To ignore calculation of the residences which "Y" size is limited. It will disable if the selection "IgnoreY" is false.
      Ignore-Y-Residences: true
      Prevent:
        # Prevent player creating multiple areas. It does not affect subzones.
        Add-Area: true
        # Prevent the residence with areas to change its size.
        Multiple-Areas-Size-Change: true
    # Permission: regionplus.points.group.GROUP
    Groups:
      # The default group. You shouldn't remove it.
      Default:
        Display: "Default"
        Limit: 10000
      MB:
        Display: "MB"
        Limit: 14400
      VIP:
        Display: "VIP"
        Limit: 25000
      MVP:
        Display: "MVP"
        Limit: 115200
      GOD:
        Display: "GOD"
        Limit: 270000
  # Reset all residences.
  # Bypass permission: regionplus.bypass.residence.reset
  # Command: /rgp residence resetall
  Reset-All:
    Settings:
      Bypass:
        Residence-List:
          - lobby
          - spawn
          - server
        Residence-Owners:
          - Momocraft
  # Reset all old residence flags to new one.
  # Bypass permission: regionplus.bypass.residence.reset
  # Command: /rgp residence resetflags
  Reset-Flags:
    Settings:
      Bypass:
        # Bypass to remove the missing custom flags.
        Missing-Custom-Flags: true
        Residence-List:
          - lobby
          - spawn
          - server
        Residence-Owners:
          - Momocraft
    Environment:
      # To remove the flags that the residence owner doesn't have permission to change.
      Remove:
        Enable: true
        Ignore-List: []
      # To add the default flag witch doesn't exist.
      Update:
        Enable: true
        Ignore-List: []
    Player:
      # To remove the flags that the residence owner doesn't have permission to change.
      Remove:
        Enable: true
        Ignore-List: []
  # Resetting all residences' enter/leave messages to default if the owners can not change it.
  # Bypass permission: regionplus.bypass.residence.reset
  # Command: /rgp residence resetmessages
  Reset-Messages:
    Settings:
      Bypass:
        Residence-List:
          - lobby
          - spawn
          - server
        Residence-Owners:
          - Momocraft
  # Toggle the feature of SurvivalMechanics.
  # Flags: climb, crawl, mobkick, roofhang, slide, swim, wallkick
  SurvivalMechanics:
    Enable: true
  # Prevent players placing the vehicles in other player's residence.
  # Prevent players picking up the vehicles if they aren't the vehicle's owner and don't have destroy permission.
  Vehicles:
    Enable: true

# Prevent players activating outside a border like visitors.
# More information: https://github.com/momoservertw/RegionPlus/wiki/Visitor
Visitor:
  Enable: false
  Settings:
    Residence:
      Enable: true
      # Allow visitor to do anything in the residences.
      Bypass: true
      # Allow visitor to create a new Residence.
      Allow-Create: false
      # Allow visitor to get a Residence from other players.
      Allow-Get: false
    Use-Item:
      Enable: true
      Message: true
      Allow-Consume: true
      Allow-Bucket: false
      Allow-Fishing: false
      # Allow visitor to use bow or potion.
      Allow-Projectile: false
      # Allow visitor to use ItemJoin's custom items.
      Allow-ItemJoin: true
    Interact-Block:
      Enable: true
      Message: true
      # Allow visitor to interact the Blocks like doors.
      Allow-Use: false
      # Allow visitor to interact the Blocks like chests.
      Allow-Container: false
    Interact-Entity:
      Enable: true
      Message: true
      Allow-NPC: true
    Damage-Entity:
      Enable: true
      Message: true
      # Allow visitor to damage other player.
      Allow-Player: true
    Drop-Item:
      Enable: true
      Message: true
    Pickup-Item:
      Enable: true
      Message: false
    # Prevent visitor dropping items when they died.
    Death-Drop:
      Message: true
      Enable: true
  Location:
    - VisitorWorlds

Message:
  prefix: "&7[&dRegionPlus&7]&r "
  Commands:
    title: "&8▩▩▩▩▩▩▩▩▩▩▩▩▩ &d&lRegionPlus &8▩▩▩▩▩▩▩▩▩▩▩▩▩"
    help: "&f/rp help &8- &7This help menu."
    reload: "&f/rp reload &8- &7Reload config file."
    version: "&f/rp version &8- &7Checks the plugin version and updates."
    flagsedit: "&f/rp flagsedit &8- &7Checks the flags of residences and edits it"
    points: "&f/rp points &8- &7Check your points limit."
    pointsOther: "&f/rp points limit <player> &8- &7Check the player's points limit."
  points: "&cPoints: &f%amount% - %group% limit: %limit%"
  pointsGroupList: "&8▩▩▩▩▩▩▩▩▩ &cResidence Points &8▩▩▩▩▩▩▩▩▩"
  targetPoints: "&c%targetplayer% Points: &f%amount% - %group% limit: %limit%"
  pointsSelect: "&7Selection size: %size%, Cost: %price%, Remaining points: %balance%"
  sizeChangeFailed: "&cThe residence with multiple areas can not change its size."
  sellFailed: "&8(Returned the money)"
  visitorResidenceCreate: "&cVisitor can't create residence!"
  visitorResidenceGet: "&cVisitor can't get a residence!"
  visitorResidenceGetTarget: "&cYou can't give the residence to Visitor!"
  visitorUseItems: "&cVisitor can't use this item!"
  visitorInteractBlocks: "&cVisitor can't interact blocks!"
  visitorInteractEntities: "&cVisitor can't interact entities!"
  visitorDamageEntities: "&cVisitor can't damage entities!"
  visitorDropItems: "&cVisitor can't drop items!"
  visitorPickupItems: "&cVisitor can't pickup items!"
  visitorDeathDrop: "&7Visitors will not drop items after death!"