# --{ =-=-=-=-=-=-=-=-=-= RegionPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
Config-Version: 1
Debugging: false
Check-Updates: true

Player:
  Prevent:
    # Prevent other plugins disable players' fly status if they have fly permission.
    # It is very useful if you are using Multiverse and allow some players flying.
    Fly-Disable:
      Enable: false
      # The permission of player to fly.
      Permission: 'cmi.command.fly'
      Location:
        - world
        - world_nether
        - world_end

Residence:
  Custom-Flags:
    # Allow potion damages entities. Default: true
    potiondamage: false
  Prevent:
    # Prevent other plugins disable players' fly status in the residence which set fly flag true.
    Fly-Disable: true
    # Prevent mobs destroy painting in the residence which set build flag false.
    Painting-Destroy: true
    # Prevent mobs destroy item_frame in the residence which set build flag false.
    Item-Frame-Destroy: true
    # Prevent mobs destroy armor_stand in the residence which set build flag false.
    Armor-Stand-Destroy: true
    # Prevent zombies destroy door in the residence which set build flag false.
    Zombie-Door-Destruction: true
    # Prevent enderman pickup block in the residence which set build flag false.
    Enderman-Pickup-Block: true
  # Using the block size to limit players' residence size just like GriefPrevention.
  Points:
    Enable: false
    Check:
      # The checking mode of points. Support: XYZ, XZ
      Mode: 'XZ'
      # It will not count the residence points if it is not infinite height.
      # It is useful for changing residence setting 'IgnoreY = false' to 'IgnoreY = true'.
      Ignore-XYZ: true
    # The default points limit if a player doesn't have any custom permission.
    # More points limit permission: regionplus.points.limit.AMOUNT
    Default-Limit: 10000
  # Edit the residence's flags.
  # Bypass permission: regionplus.bypass.flagedit
  Flag-Editor:
    Enable: false
    # Automatic check the flags when the server is starting.
    Auto-Check:
      Enable: false
      Delay: 20
    Default:
      # Add the flag that the default setting does exist but the residence does not exist.
      Update: true
      # Remove the flag that the default setting does not exist and the owner does not have permission to change it.
      Remove-No-Perms: true
    Permission:
      # Remove the flag that the owner does not have permission to change it.
      Remove-No-Perms: true

# Prevent general players build or kill entities outside the border.
# Bypass permission: regionplus.bypass.visitor.WORLD
Visitor:
  Enable: false
  # The visitor border of the world.
  Border:
    world:
      Range:
        R: 10000
  Prevent:
    Ignore:
      # Visitors can only build or damage entities in the residence which they has permissions.
      Has-Residence-Permissions: true
    List:
      # Prevent visitors to create residences.
      # Need plugin: Residence
      Create-Residence:
        Enable: true
        # Send message when cancel the event.
        Message: true
      # Prevent visitors to use items.
      Use-Items:
        Enable: false
        Message: true
        # Allows eat foods or drink potion.
        Allow-Consume: true
        # Allows bucket water or lava.
        Allow-Bucket: false
        # Allows shoot arrows or throw potions.
        Allow-Projectile: false
        # Allows using fishing rod.
        Allow-Fishing: false
        # Need plugin: ItemJoin
        Allow-ItemJoin: true
      # Prevent visitors to click a block.
      Interact-Blocks:
        Enable: true
        Message: true
        # Allow visitors to use interact some blocks like doors.
        Allow-Use: false
        # Allow visitors to open containers like chest.
        Allow-Container: false
      # Prevent visitors to right click entities.
      Interact-Entities:
        Enable: true
        Message: true
        # Allow visitors to right click npc.
        Allow-NPC: true
      # Prevent visitors to damage entities.
      Damage-Entities:
        Enable: true
        Message: true
        # Allow visitors to damage other players.
        Allow-Player: true
      # Prevent visitors to drop items.
      Drop-Items:
        Enable: true
        Message: true
      # Prevent visitors to pickup items.
      Pickup-Items:
        Enable: true
        Message: true

Message:
  prefix: '&7[&dRegionPlus&7]&r '
  noPermission: '&cYou do not have permission to use that command!'
  configReload: '&aConfiguration(s) Reloaded!'
  unknownCommand: '&cUnknown command, See &e/regionplus help &cfor a list of commands.'
  targetNotOnline: '&cPlayer &e%targetplayer% &cdoesn''t online!'
  RegionPlus:
    Commands:
      title: '&8▩▩▩▩▩▩▩▩▩▩▩▩▩ &d&lRegionPlus &8▩▩▩▩▩▩▩▩▩▩▩▩▩'
      help: '&a/rp help &8- &7This help menu.'
      reload: '&a/rp reload &8- &7Reload config file.'
      version: '&f/rp version &8- &7Checks the plugin version and updates.'
      flagedit: '&f/rp flagedit &8- &7Checks the flags of residences and edits it'
      pointsLimit: '&a/rp points limit &8- &7Check your residence points limit.'
      pointsLimitOther: '&a/rp points limit <player> &8- &7Check the player''s residence points limit.'
      pointsUsed: '&a/rp points used &8- &7Check how many points you have used.'
      pointsUsedOther: '&a/rp points used <player> &8- &7Check how many points the player has used.'
      pointsLook: '&a/rp points look &8- &7Check your remaining residence points.'
      pointsLookOther: '&a/rp points look <player> &8- &7Check the player''s remaining residence points.'
    pointsLimit: '&eYour residence points limit &8- &f%points_limit%'
    targetPointsLimit: '&eYour residence points limit &8- &f%points_limit%'
    pointsUsed: '&eYour used points &8- &f%points_used%'
    targetPointsUsed: '&e%targetplayer% used points &8- &f%points_used%'
    pointsRemainder: '&eYour remaining residence points &8- &f%points_remainder%'
    targetPointsRemainder: '&e%targetplayer% remaining residence points &8- &f%points_remainder%'
    notEnoughPoints: '&cYou dont have enough residence points &8- &8(&e%points_need%&f/&6%points_limit%&8)'
    targetNotEnoughPoints: '&c%targetplayer% doesn''t have enough residence points.'
    visitorCreateResidence: '&cVisitor can''t create residence there!'
    visitorUseItems: '&cVisitor can''t use this item there!'
    visitorInteractBlocks: '&cVisitor can''t interact blocks there!'
    visitorInteractEntities: '&cVisitor can''t interact entities there!'
    visitorDamageEntities: '&cVisitor can''t damage entities there!'
    visitorDropItems: '&cVisitor can''t drop items there!'
    visitorPickupItems: '&cVisitor can''t pickup items there!'