# --{ =-=-=-=-=-=-=-=-=-= RegionPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
# Wiki: https://github.com/momoservertw/RegionPlus/wiki
Config-Version: 4
Check-Updates: true
Debugging: false

# Adding more features for Residence.
# More information: https://github.com/momoservertw/RegionPlus/wiki/Residence
Residence:
  Enable: false
  Settings:
    # It will check every areas in one residence. Because of two area may in the same location, I'm not recommend using multiple areas.
    # You can set the "MaxAreasPerResidence: 0" in residence groups.yml  to prevent players creating multiple areas.
    # And only use subzone to allow players to set different residence permissions.
    All-Areas:
      Enable: false
      # Ignore the area which is in another area.
      Ignore-Within-Area: false
  # Fixed some bugs and improved the player's gaming experience.
  Prevent:
    Enable: true
    Potion-Damage: true
    Painting-Destroy: true
    Item-Frame-Destroy: true
    Armor-Stand-Destroy: true
    Zombie-Door-Destruction: true
    Enderman-Pickup-Block: true
    Block-Damage: true
  # Limit the total size of player's residences.
  Points:
    Enable: false
    Settings:
      Select-Info: true
      # For the server who changed the Residence "IgnoreY" from false to true.
      Not-Ignore-Y-Residences:
        Enable: false
        Points-Calculate: false
        Prevent-Add-Area: false
        Prevent-Change-Size: false
    # Permission: regionplus.points.group.GROUP
    Groups:
      # The default group. You shouldn't remove it.
      Default:
        Display: "&a&lDefault"
        Limit: 10000
      MB:
        Display: "&a&lMB"
        Limit: 14400
      VIP:
        Display: "&b&lVIP"
        Limit: 25000
      MVP:
        Display: "&d&lMVP"
        Limit: 115200
      GOD:
        Display: "&e&lGOD"
        Limit: 270000
  # Changing all old residence flags to new one.
  Flags-Editor:
    Enable: true
    Settings:
      Bypass:
        # Bypass permission: regionplus.bypass.flagsedit
        Permission: true
        # Bypass to remove the missing custom flags.
        Missing-Custom-Flags: true
      # It will delay few seconds and restart editing flags to prevent the server restart while editing flags.
      Max-Edit-Players:
        # Set "0" to disable this feature.
        Limit: 30
        # The delay seconds of restart editing flags.
        Interval: 1
        Message: true
    # Checking the "Flags.Default" in groups.yml.
    Default:
      # Remove the flags that doesn't exist.
      Remove:
        Enable: true
        # Only remove the flags that residence owner doesn't have permission to change.
        Only-No-Perms: true
        Ignore-List: []
      # Add the flags that does exist but the residence doesn't have.
      Update:
        Enable: true
        Ignore-List: []
    # Checking the "Flags.Permission" in groups.yml.
    Permissions:
      # Remove the flags that the residence owner doesn't have permission to change.
      Remove:
        Enable: true
        Ignore-List: []
  # Resetting all old residences' enter/leave messages to default.
  # It will be cool to show title bar when players enter residences.
  # TitleBar Example
  # Enter: "&e&lEnter &f%residence %subtitle% &6&lOwner &6%owner"
  # Leave: "&7Left..."
  Message-Editor:
    Enable: true
    Settings:
      Bypass:
        # Bypass permission: regionplus.bypass.messageedit
        Permission: true
      # Showing the editing progress.
      Message: true
    # By default, it will only change the matching messages.
    Groups:
      # Changing messages for difference groups
      # Support multiple lines and if you set the message to "[]", it will force to reset every messages in that group.
      default:
        Enter:
          - "Welcome %player to %residence, owned by %owner."
        Leave:
          - "Now leaving %residence."
      vip:
        Enter:
          - "Welcome %player to %residence, owned by %owner."
        Leave:
          - "Now leaving %residence."
    # Toggle the feature of SurvivalMechanics.
    SurvivalMechanics:
      Enable: true
      Custom-Flags:
        Climb: true
        Crawl: true
        Mobkick: true
        Roofhang: true
        Slide: true
        Swim: true
        Wallkick: true
    # Pickup vehicles: build
    # Place vehicles: build
    # Ride vehicles: use
    Vehicles:
      Enable: true

# Prevent players activating outside a location like visitors.
# More information: https://github.com/momoservertw/RegionPlus/wiki/Visitor
Visitor:
  Enable: false
  Settings:
    # Sending the prevent message to visitors.
    Message: true
    Residence:
      Enable: true
      # Allow to do something if player has that permission flag.
      Allow-Has-Permission: true
      # Allow to create new Residence.
      Allow-Create: false
      # Allow to expand or contract the Residence.
      Allow-Change-Size: true
    Use-Item:
      Enable: true
      Allow-Consume: true
      Allow-Bucket: false
      Allow-Fishing: false
      # Allow to use bow or potion.
      Allow-Projectile: false
      # Allow to use ItemJoin's custom items.
      Allow-ItemJoin: true
    Interact-Block:
      Enable: true
      # Allow to use the Blocks like open a door.
      Allow-Use: false
      # Allow to use the Blocks like open a chest.
      Allow-Container: false
    Interact-Entity:
      Enable: true
      Allow-NPC: true
    Damage-Entity:
      Enable: true
      # Allow to damage other player.
      Allow-Player: true
    Drop-Item:
      Enable: true
    Pickup-Item:
      Enable: true
    # Disabled dropping items when they died.
    Death-Drop:
      Enable: true
  Location:
    - VisitorWorlds

Message:
  prefix: "&7[&dRegionPlus&7]&r "
  Commands:
    title: "&8▩▩▩▩▩▩▩▩▩▩▩▩▩ &d&lRegionPlus &8▩▩▩▩▩▩▩▩▩▩▩▩▩"
    help: "&f/rp help &8- &7This help menu."
    reload: "&f/rp reload &8- &7Reload config file."
    version: "&f/rp version &8- &7Checks the plugin version and updates."
    flagsedit: "&f/rp flagsedit &8- &7Checks the flags of residences and edits it"
    points: "&f/rp points &8- &7Check your points limit."
    pointsOther: "&f/rp points limit <player> &8- &7Check the player's points limit."
  points: "&cPoints: &f%amount% - %group% limit: %limit%"
  pointsGroupList: "&8▩▩▩▩▩▩▩▩▩ &cResidence Points &8▩▩▩▩▩▩▩▩▩"
  targetPoints: "&c%targetplayer% Points: &f%amount% - %group% limit: %limit%"
  pointsSelect: "&7Selection size: %size%, Cost: %price%, Remaining points: %balance%"
  sellFailed: "&8(Returned the money)"
  sizeChangeFailed: "&cYou can not change this residence size."
  visitorResidenceCreate: "&cVisitor can't create residence!"
  visitorResidenceSize: "&cVisitor can't change residence size!"
  visitorUseItems: "&cVisitor can't use this item!"
  visitorInteractBlocks: "&cVisitor can't interact blocks!"
  visitorInteractEntities: "&cVisitor can't interact entities!"
  visitorDamageEntities: "&cVisitor can't damage entities!"
  visitorDropItems: "&cVisitor can't drop items!"
  visitorPickupItems: "&cVisitor can't pickup items!"