# --{ =-=-=-=-=-=-=-=-=-= RegionPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
Config-Version: 2
Debugging: false
Check-Updates: true

# Add the block size limit in residence areas, update old flags in batches and fix bugs.
# Need plugin: Residence
Residence:
  Prevent:
    Enable: false
    # Prevent potions from killing animals, monsters, and players without residence flags or enabling PVP status in the residence (requires: PvPManager).
    Potion-Damage: true
    # Prevent entities(contains TNT) from destroying paintings in residences without build flag.
    Painting-Destroy: true
    # Prevent entities(contains TNT) from destroying item_frames in residences without build flag.
    Item-Frame-Destroy: true
    # Prevent entities(contains TNT) from destroying Armor_Stand in residences without build flag.
    Armor-Stand-Destroy: true
    # Prevent zombies from destroying doors in residences without build flag.
    Zombie-Door-Destruction: true
    # Prevent enderman from picking up blocks in residences without build flag.
    Enderman-Pickup-Block: true
  # Using the blocks size to limit players' residence size just like GriefPrevention.
  Points:
    Enable: false
    Check:
      # The calculate mode of points. Support: XYZ, XZ
      Mode: 'XZ'
      # It will not count the points if the residence are not infinite height. It is useful for changing residence "IgnoreY" setting 'false' to 'true'.
      Ignore-XYZ: true
      # Return the difference cost between IgnoreY "false" and "true" if you changed it.
      Return-XYZ: true
      # It will check every areas in one residence. Because of two area may in the same location, I'm not recommend using multiple areas.
      # You can set the "MaxAreasPerResidence: 0" in residence groups.yml  to prevent players creating multiple areas.
      # And only use subzone to allow players to set different residence permissions.
      All-Areas:
        Enable: false
        # Ignore the area which is in another area.
        Ignore-Within-Area: false
    # The default points for difference groups. You can add your own groups.
    # Permission: regionplus.points.group.GROUP
    Groups:
      # The default group. You shouldn't remove it.
      Default:
        # The placeholder of "%points_group%" in message.
        Display: "&a&lDefault"
        # The number of block limit.
        Limit: 10000
      MB:
        Display: "&a&lMB"
        Limit: 14400
      VIP:
        Display: "&b&lVIP"
        Limit: 25000
      MVP:
        Display: "&d&lMVP"
        Limit: 115200
      GOD:
        Display: "&e&lGOD"
        Limit: 270,000

  # Changing all old residence flag to new one.
  # Bypass permission: regionplus.bypass.flagsedit
  Flags-Editor:
    Enable: false
    # It will delay 3 seconds and restart editing flags to prevent the server restart while editing flags. Set "0" to disable this feature.
    Max-Edit-Players: 100
    # Automatic check the flags when the server is starting.
    Auto-Check:
      Enable: false
      Delay: 20
    Default:
      # Add the flag that default setting does exist but the residence doesn't exist.
      Update: true
      # Remove the flag that default setting doesn't exist and the residence owner doesn't have permission to change.
      Remove-No-Perms: true
    Permissions:
      # Remove the flag that the residence owner doesn't have permission to change.
      Remove-No-Perms: true

# Prevent general players build or kill entities outside the border.
# Bypass permission: regionplus.bypass.visitor.WORLD
Visitor:
  Enable: false
  # The visitor border of worlds.
  # More information: https://github.com/momoservertw/RegionPlus/wiki/Location
  Border:
    world:
      R: 10000
  Prevent:
    Ignore:
      # Visitors can only build or damage entities in a residence which they has permissions.
      Has-Residence-Permissions: true
    List:
      # Prevent visitors to create residences.
      Create-Residence:
        Enable: true
        # Send message when cancel the event.
        Message: true
      # Prevent visitors to use items.
      Use-Items:
        Enable: true
        Message: true
        # Allows eat foods or drink potion.
        Allow-Consume: true
        # Allows bucket and place water or lava.
        Allow-Bucket: false
        # Allows shoot arrows or throw potions.
        Allow-Projectile: false
        # Allows fishing.
        Allow-Fishing: false
        # Allows use custom items.
        # Need plugin: ItemJoin
        Allow-ItemJoin: true
      # Prevent visitors to click blocks.
      Interact-Blocks:
        Enable: true
        Message: true
        # Allow visitors to use some blocks like doors.
        Allow-Use: false
        # Allow visitors to open containers like chest.
        Allow-Container: false
      # Prevent visitors to right click entities.
      Interact-Entities:
        Enable: true
        Message: true
        # Allow visitors to right click npc.
        Allow-NPC: true
      # Prevent visitors to damage entities.
      Damage-Entities:
        Enable: true
        Message: true
        # Allow visitors to damage other players.
        Allow-Player: true
      # Prevent visitors to drop items.
      Drop-Items:
        Enable: true
        Message: true
      # Prevent visitors to pickup items.
      Pickup-Items:
        Enable: true
        Message: true

Message:
  prefix: '&7[&dRegionPlus&7]&r '
  noPermission: '&cYou do not have permission to use that command!'
  configReload: '&aConfiguration(s) Reloaded!'
  unknownCommand: '&cUnknown command, See &e/regionplus help &cfor a list of commands.'
  targetNotOnline: '&cPlayer &e%targetplayer% &cdoesn''t online!'
  RegionPlus:
    Commands:
      title: '&8▩▩▩▩▩▩▩▩▩▩▩▩▩ &d&lRegionPlus &8▩▩▩▩▩▩▩▩▩▩▩▩▩'
      help: '&f/rp help &8- &7This help menu.'
      reload: '&f/rp reload &8- &7Reload config file.'
      version: '&f/rp version &8- &7Checks the plugin version and updates.'
      flagsedit: '&f/rp flagsedit &8- &7Checks the flags of residences and edits it'
      pointsLimit: '&f/rp points limit &8- &7Check your points limit.'
      pointsLimitOther: '&f/rp points limit <player> &8- &7Check the player''s points limit.'
      pointsUsed: '&f/rp points used &8- &7Check how many points you have used.'
      pointsUsedOther: '&f/rp points used <player> &8- &7Check how many points the player has used.'
      pointsLook: '&f/rp points look &8- &7Check your remaining points.'
      pointsLookOther: '&f/rp points look <player> &8- &7Check the player''s remaining points.'
    points: '&e&lPoints: &f%points_remainder% &8- &7【%points_group%&7】 &6%points_used%&7/&c%points_limit%'
    targetPoints: '&e&l%targetplayer%''s Points: &f%points_remainder% &8- &7【%points_group%&7】 &6%points_used%&7/&c%points_limit%'
    pointsSelete: '&eSelection total size: &6%res_size& &eLand cost: &6%res_size& /n &e&lNeed points: &f%points_need% &8- &6%points_remainder% &8➸ &c%points_newremainder%'
    notEnoughPoints: '&cYou dont have enough points &8- &8(&e%points_need%&f/&6%points_remainder%&8)'
    targetNotEnoughPoints: '&c%targetplayer% doesn''t have enough points.'
    visitorCreateResidence: '&cVisitor can''t create residence here!'
    visitorUseItems: '&cVisitor can''t use this item here!'
    visitorInteractBlocks: '&cVisitor can''t interact blocks here!'
    visitorInteractEntities: '&cVisitor can''t interact entities here!'
    visitorDamageEntities: '&cVisitor can''t damage entities here!'
    visitorDropItems: '&cVisitor can''t drop items here!'
    visitorPickupItems: '&cVisitor can''t pickup items here!'