# ░░░░░░░░░░░░░░░   RegionPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/regionplus.76878/
#  Wiki: https://github.com/momoservertw/RegionPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 4
Debugging: false
Check-Updates: true

General:
  Features:
    # Changed these options need to restart the server.
    Hook:
      Residence: true
      SurvivalMechanics: true
      Vehicles: true

# Adding some features to improve CMI and Residence.
# More information: https://github.com/momoservertw/RegionPlus/wiki/World-Control
World-Contorl:
  Enable: false
  Prevent:
    Enable: true
    Block-Damage:
      Enable: true
      Ignore-List:
        - TNT
    Dropped-Item-Damage:
      Explosion: true

# Adding more features for Residence.
# More information: https://github.com/momoservertw/RegionPlus/wiki/Residence
Residence:
  Enable: false
  # Fixed some bugs and improved the player's gaming experience.
  Prevent:
    Enable: true
    Potion-Damage: true
    Zombie-Door-Destruction: true
    Enderman-Pickup-Block: true
    Painting-Destroy: true
    Item-Frame-Destroy: true
    Armor-Stand-Destroy: true
    Ender-Crystal-Destroy: true
    Block-Damage: true
  # To limit the total size of player's residences.
  # This feature will only calculate the main area size.
  # Please set the "MaxAreasPerResidence" to "1" in Residence group.yml to prevent they have multiple areas.
  # Permission: regionplus.points.number.NUMBER
  Points:
    Enable: false
    Settings:
      Select-Info: true
      # To ignore calculation of the residences which "Y" size is limited. Only works when the residence.
      Limited-Y-Calculate: false
      Prevent:
        # Prevent changing the size of residence which has multiple areas.
        Multiple-Areas-Size-Change: true
        # Prevent changing the size of residence which is limited "Y".
        Limited-Y-Size-Change: true
    # Specify the limit for difference players.
    # Permission: regionplus.points.group.GROUP
    Groups:
      # The default group. You shouldn't remove it.
      Default:
        Display: "Default"
        Limit: 10000
      VIP:
        Display: "VIP"
        Limit: 25000
      MVP:
        Display: "MVP"
        Limit: 115200
    # Players will get more points if they upgraded their residence level.
    # Based on the permission: regionplus.points.level.LEVEL
    # Increase: /regionplus points promote [number]
    # Decrease: /regionplus points demote [number]
    Level:
      Increase: 1000
      Display: "+%level%"
  # Updating all old residences' flags to new one.
  # Command: /rgp residence updateflags
  Update-Flags:
    Settings:
      Bypass:
        # Bypass to remove the missing custom flags from other plugins.
        Missing-Custom-Flags: true
        Residence-List:
          - lobby
          - spawn
          - server
        Residence-Owners:
          - Momocraft
    Environment:
      # To remove the flags that the residence owner doesn't have permission to change.
      Remove:
        Enable: true
        Ignore-List: []
      # To add the missing default flags.
      Update:
        Enable: true
        Ignore-List: []
    Player:
      # To remove the flags that the residence owner doesn't have permission to change.
      Remove:
        Enable: true
        Ignore-List: []
  # Updating all residences' enter/leave messages to default if the owner has no permission to change it.
  # Command: /rgp residence updatemessages
  Update-Messages:
    Bypass:
      Residence-List:
        - lobby
        - spawn
        - server
      Residence-Owners:
        - Momocraft
    Old-Message:
      Enter-List:
        - "Welcome %player to %residence, owned by %owner."
      Leave-List:
        - "Now leaving %residence."

  # Toggle the feature of SurvivalMechanics in residences.
  # Custom flags: climb, crawl, mobkick, roofhang, slide, swim, wallkick
  # More information: https://github.com/momoservertw/RegionPlus/wiki/SurvivalMechanics
  # SurvivalMechanics: https://www.spigotmc.org/resources/%E2%96%91-survivalmechanics-%E2%96%91-1-9-x-1-16-x-%E2%96%91.26156/
  SurvivalMechanics:
    Enable: true
  # Control the permission of Vehicles in a residence.
  # More information: https://github.com/momoservertw/RegionPlus/wiki/Vehicles
  # Vehicles: https://www.spigotmc.org/resources/%E2%9C%88%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/
  Vehicles:
    Enable: true

# Prevent players activating in location like visitors.
# Useful if you want to limit the world border to new players.
# More information: https://github.com/momoservertw/RegionPlus/wiki/Visitor
Visitor:
  Enable: false
  Settings:
    Residence:
      Enable: true
      # Allow new players to live with the old players.
      Bypass: true
      # Allow visitor to create a new Residence.
      Allow-Create: false
      # Allow visitor to get a Residence.
      Allow-Get: false
    Use-Item:
      Enable: true
      Message: true
      Allow-Consume: true
      Allow-Bucket: false
      Allow-Fishing: false
      # Allow visitor to use bow or potion.
      Allow-Projectile: false
      # Allow visitor to use ItemJoin's custom items.
      Allow-ItemJoin: true
    Interact-Block:
      Enable: true
      Message: true
      # Allow visitor to interact the Blocks like doors.
      Allow-Use: false
      # Allow visitor to interact the Blocks like chests.
      Allow-Container: false
    Interact-Entity:
      Enable: true
      Message: true
      Allow-NPC: true
    Damage-Entity:
      Enable: true
      Message: true
      # Allow visitor to damage other player.
      Allow-Player: true
    Drop-Item:
      Enable: true
      Message: true
    Pickup-Item:
      Enable: true
      Message: false
    # Prevent visitor dropping items when they died.
    Death-Drop:
      Message: true
      Enable: true
  Location:
    - VisitorWorlds