# --{ =-=-=-=-=-=-=-=-=-= RegionPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
Config-Version: 2
Debugging: false
Check-Updates: true

# Add the block size limit in residence areas, update old flags in batches and fix bugs.
# Need plugin: Residence
Residence:
  Settings:
    # It will check every areas in one residence. Because of two area may in the same location, I'm not recommend using multiple areas.
    # You can set the "MaxAreasPerResidence: 0" in residence groups.yml  to prevent players creating multiple areas.
    # And only use subzone to allow players to set different residence permissions.
    All-Areas:
      Enable: false
      # Ignore the area which is in another area.
      Ignore-Within-Area: false
  # Return the difference money between IgnoreY "false" to "true" if you changed it.
  Return-XYZ: false
  Prevent:
    Enable: false
    # Prevent potions from killing animals, monsters, and players without residence flags or enabling PVP status in the residence (requires: PvPManager).
    Potion-Damage: true
    # Prevent entities(contains TNT) from destroying paintings in residences without build flag.
    Painting-Destroy: true
    # Prevent entities(contains TNT) from destroying item_frames in residences without build flag.
    Item-Frame-Destroy: true
    # Prevent entities(contains TNT) from destroying Armor_Stand in residences without build flag.
    Armor-Stand-Destroy: true
    # Prevent zombies from destroying doors in residences without build flag.
    Zombie-Door-Destruction: true
    # Prevent enderman from picking up blocks in residences without build flag.
    Enderman-Pickup-Block: true
  # Using the blocks size to limit players' residence size just like GriefPrevention.
  Points:
    Enable: false
    # Send points message when using residence select tool.
    Select-Info: true
    Check:
      # It will not count the points if the residence are not infinite height. It is useful for changing residence "IgnoreY" setting 'false' to 'true'.
      Ignore-XYZ: true
    # The residence block limit for difference groups. You can add your own groups.
    # Permission: regionplus.points.group.GROUP
    Groups:
      # The default group. You shouldn't remove it.
      Default:
        # The placeholder of "%points_group%" in message.
        Display: '&a&lDefault'
        # The number of block limit.
        Limit: 10000
      MB:
        Display: '&a&lMB'
        Limit: 14400
      VIP:
        Display: '&b&lVIP'
        Limit: 25000
      MVP:
        Display: '&d&lMVP'
        Limit: 115200
      GOD:
        Display: '&e&lGOD'
        Limit: 270000
  # Changing all old residence flag to new one.
  # Bypass permission: regionplus.bypass.flagsedit
  Flags-Editor:
    Enable: false
    Settings:
      # Automatic check the flags when the server is starting.
      Auto-Check:
        Enable: false
        Delay: 20
      # It will delay few seconds and restart editing flags to prevent the server restart while editing flags.
      Max-Edit-Players:
        # Set "0" to disable this feature.
        Limit: 30
        # The delay seconds of restart editing flags.
        Interval: 1
        # The restart editing messages.
        Message: true
      # Bypass to remove the missing custom flags.
      Bypass-Missing-Custom-Flags: true
      Check-Bypass-Permission: true
    # Checking the "Flags.Default" in groups.yml.
    Default:
      # Remove the flags that doesn't exist.
      Remove:
        Enable: true
        # Only remove the flags that residence owner doesn't have permission to change.
        Only-No-Perms: true
        Ignore-List: []
      # Add the flags that does exist but the residence doesn't have.
      Update:
        Enable: true
        Ignore-List: []
    # Checking the "Flags.Permission" in groups.yml.
    Permissions:
      # Remove the flags that the residence owner doesn't have permission to change.
      Remove:
        Enable: true
        Ignore-List: []

# Prevent general players build or kill entities outside the border.
# Bypass permission: regionplus.bypass.visitor.WORLD
Visitor:
  Enable: false
  # The visitor border of worlds.
  # More information: https://github.com/momoservertw/RegionPlus/wiki/Location
  Border:
    world:
      "!R": 10000
  Prevent:
    Ignore:
      # Visitors can only build or damage entities in a residence which they has permissions.
      Has-Residence-Permissions: true
    List:
      # Prevent visitors to create residences.
      Create-Residence:
        Enable: true
        # Send message when cancel the event.
        Message: true
      # Prevent visitors to use items.
      Use-Items:
        Enable: true
        Message: true
        # Allows eat foods or drink potion.
        Allow-Consume: true
        # Allows bucket and place water or lava.
        Allow-Bucket: false
        # Allows shoot arrows or throw potions.
        Allow-Projectile: false
        # Allows fishing.
        Allow-Fishing: false
        # Allows use custom items.
        # Need plugin: ItemJoin
        Allow-ItemJoin: true
      # Prevent visitors to click blocks.
      Interact-Blocks:
        Enable: true
        Message: true
        # Allow visitors to use some blocks like doors.
        Allow-Use: false
        # Allow visitors to open containers like chest.
        Allow-Container: false
      # Prevent visitors to right click entities.
      Interact-Entities:
        Enable: true
        Message: true
        # Allow visitors to right click npc.
        Allow-NPC: true
      # Prevent visitors to damage entities.
      Damage-Entities:
        Enable: true
        Message: true
        # Allow visitors to damage other players.
        Allow-Player: true
      # Prevent visitors to drop items.
      Drop-Items:
        Enable: true
        Message: true
      # Prevent visitors to pickup items.
      Pickup-Items:
        Enable: true
        Message: true

Message:
  prefix: '&7[&dRegionPlus&7]&r '
  noPermission: '&cYou do not have permission to use that command!'
  configReload: '&aConfiguration(s) Reloaded!'
  unknownCommand: '&cUnknown command, See &e/regionplus help &cfor a list of commands.'
  targetNotOnline: '&cPlayer &e%targetplayer% &cdoesn''t online!'
  featureNotEnable: '&cServer does not enable this feature.'
  RegionPlus:
    Commands:
      title: '&8▩▩▩▩▩▩▩▩▩▩▩▩▩ &d&lRegionPlus &8▩▩▩▩▩▩▩▩▩▩▩▩▩'
      help: '&f/rp help &8- &7This help menu.'
      reload: '&f/rp reload &8- &7Reload config file.'
      version: '&f/rp version &8- &7Checks the plugin version and updates.'
      flagsedit: '&f/rp flagsedit &8- &7Checks the flags of residences and edits it'
      pointsLimit: '&f/rp points limit &8- &7Check your points limit.'
      pointsLimitOther: '&f/rp points limit <player> &8- &7Check the player''s points limit.'
      pointsUsed: '&f/rp points used &8- &7Check how many points you have used.'
      pointsUsedOther: '&f/rp points used <player> &8- &7Check how many points the player has used.'
      pointsLook: '&f/rp points look &8- &7Check your remaining points.'
      pointsLookOther: '&f/rp points look <player> &8- &7Check the player''s remaining points.'
    points: '&e&lPoints: &f%points_last% &8- &7【%points_group%&7】 &6%points_used%&7/&c%points_limit% /n &7Next group &7【%points_nextgroup%&7】 &8- &e%points_limit% &8➸ &d%points_nextlimit% &7(+%points_nextbonus%)'
    targetPoints: '&e&l%targetplayer%''s Points: &f%points_last% &8- &7【%points_group%&7】 &6%points_used%&7/&c%points_limit%'
    pointsSelect: '&eSelection total size: &6%points_need%  &eLand cost: &6%res_cost% /n &e&lNeed points: &f%points_need% &8- &6%points_last% &8➸ &c%points_newlast%'
    notEnoughPoints: '&cYou don''t have enough points &8- &8(&e%points_need%&f/&6%points_last%&8)'
    targetNotEnoughPoints: '&c%targetplayer% doesn''t have enough points.'
    transactionFailed: '&cThe transaction fails and the money is returned.'
    returnXYZMoney: '&6Get the difference of $%amount% on removed a old residence.'
    visitorCreateResidence: '&cVisitor can''t create residence here!'
    visitorUseItems: '&cVisitor can''t use this item here!'
    visitorInteractBlocks: '&cVisitor can''t interact blocks here!'
    visitorInteractEntities: '&cVisitor can''t interact entities here!'
    visitorDamageEntities: '&cVisitor can''t damage entities here!'
    visitorDropItems: '&cVisitor can''t drop items here!'
    visitorPickupItems: '&cVisitor can''t pickup items here!'