name: RegionPlus
main: tw.momocraft.regionplus.RegionPlus
author: Momocraft
api-version: 1.13
version: 1.0.2
description: Visitor system and adding more features for Residence.
softdepend: [Vault, Residence, PlaceHolderAPI, ItemJoin, PvPManager, LuckPerms, SurvivalMechanics]

commands:
  regionplus:
    description: Displays main command menu.
    permission: regionplus.use
    aliases: [rp]
    usage: |
      /regionplus

permissions:
  regionplus.*:
    description: Allows use of all commands and feature.
    default: op
  regionplus.all:
    description: Allows use of all commands and feature.
    default: op
    children:
      regionplus.use: true
      regionplus.command.*: true
      regionplus.bypass.*: true
      regionplus.points.group.*: true
  regionplus.use:
    description: Allows use of basic commands.
    default: true
  regionplus.command.*:
    description: Allows use all commands.
    default: op
    children:
      regionplus.command.reload: true
      regionplus.command.version: true
      regionplus.command.flagsedit: true
      regionplus.command.messageedit: true
      regionplus.command.points: true
      regionplus.command.points.other: true
  regionplus.command.reload:
    description: Allows use of command /regionplus reload.
    default: op
  regionplus.command.version:
    description: Allows use of command /regionplus version.
    default: op
  regionplus.command.flagsedit:
    description: Allows use of command /regionplus flagsedit.
    default: op
  regionplus.command.messageedit:
    description: Allows use of command /regionplus messageedit.
    default: op
  regionplus.command.points:
    description: Allows use of command /regionplus points.
    default: op
  regionplus.command.points.other:
    description: Allows use of command /regionplus points <player>.
    default: op
  regionplus.bypass.*:
    description: Allows player to bypass all features.
    default: op
    children:
      regionplus.bypass.points.limit: true
      regionplus.bypass.visitor.*: true
      regionplus.bypass.flagsedit: true
      regionplus.bypass.messageedit: true
  regionplus.bypass.points.limit:
    description: Allows player to bypass points limit.
    default: op
  regionplus.bypass.visitor.*:
    description: Allows player to bypass all worlds of visitor limits.
    default: op
    children:
      regionplus.bypass.visitor.world: true
      regionplus.bypass.visitor.world_nether: true
      regionplus.bypass.visitor.world_the_end: true
  regionplus.bypass.visitor.world:
    description: Allows player to bypass the world of visitor limits.
    default: op
  regionplus.bypass.visitor.world_nether:
    description: Allows player to bypass the world of visitor limits.
    default: op
  regionplus.bypass.visitor.world_the_end:
    description: Allows player to bypass the world of visitor limits.
    default: op
  regionplus.bypass.flagsedit:
    description: Allows player to bypass the residence flags editor.
    default: op
  regionplus.bypass.messageedit:
    description: Allows player to bypass the residence message editor.
    default: op
  regionplus.points.group.default:
    description: Sets player's points group to default.
    default: op
  regionplus.points.group.*:
    description: Sets player's points group to highest one.
    default: op
  regionplus.points.group.mb:
    description: Sets player's points group to mb.
    default: op
  regionplus.points.group.vip:
    description: Sets player's points group to vip.
    default: op
  regionplus.points.group.mvp:
    description: Sets player's points group to mvp.
    default: op
  regionplus.points.group.god:
    description: Sets player's points group to god.
    default: op